### ISSUE TITLE
Remove rule `@typescript-eslint/require-await`

### ISSUE THREAD

**Issue by swansontec** [standard/eslint-config-standard-with-typescript#249] opened 2020-03-16 22:12 UTC
**What version of this package are you using?**

v14

**What problem do you want to solve?**

The upstream Standard.js project has access to the `require-await` rule in plain-old ESLint, but has chosen not to activate it. Indeed, they have already [discussed this rule and rejected it](https://github.com/standard/standard/issues/738).

The arguments there are just as valid in Javascript as well as Typescript. In addition, both @LinusU and myself have run into the exact same footgun when using this rule (#217, #158).

I realize that eslint-config-standard-with-typescript includes many rules that upstream does not, since we have access to type information. However, in cases where there is a 1:1 match between the Typescript rule and the ESLint rule, I think we should leave the decision to upstream, since it's just as valuable or harmful there as it is here.

**What do you think is the correct solution to this problem?**

Remove `@typescript-eslint/require-await`.

**Are you willing to submit a pull request to implement this change?**

Of course.

**Comment by LinusU** [comment] 2020-03-17 11:03
This is the ecosystem breakage report for normal Standard:

```text
1..219
# tests 219
# pass  212
# fail  7
```

Three of the fails only had rule violations in test/example code.

-----

That being said, I would still be open to removing this rule, but was convinced to keep it last time it was discussed 😅

**Comment by mightyiam** [comment] 2020-03-17 11:28
Thank you, @swansontec. This is a duplicate of #217. Please discuss there with new arguments. Specifically, I'm pleased with the conclusion of https://github.com/standard/eslint-config-standard-with-typescript/issues/217#issuecomment-582249224.

**Comment by mightyiam** [comment] 2020-03-17 11:28
@LinusU thank you. That is helpful.

**Closed by mightyiam** 2020-03-17 11:28 UTC
