### ISSUE TITLE
No lint issue reports for Vue files using Typescript

### ISSUE THREAD

**Issue by AndreasNasman** [standard/eslint-config-standard-with-typescript#552] opened 2021-04-06 06:29 UTC
**What version of this package are you using?**
20.0.0

**What operating system, Node.js, and npm version?**
macOS Big Sur version 11.2.3, 14.16.0/15.13.0, 6.14.11/7.7.6

**What happened?**
When trying to lint `.vue` files with `<script lang="ts">` tags, no errors/warnings are observed. Adding code smells to a `.ts` file reports errors/warnings correctly, but the same flaws added to a `.vue` file are omitted. This is the `.eslintrc.js` file I used:

```js
module.exports = {
  env: {
    browser: true,
    es2021: true,
    node: true
  },
  extends: [
    'plugin:vue/vue3-essential',
    'standard-with-typescript',
    'prettier'
  ],
  parserOptions: {
    extraFileExtensions: ['.vue'],
    parser: '@typescript-eslint/parser',
    project: './tsconfig.json',
    sourceType: 'module'
  },
  plugins: [
    'vue',
    '@typescript-eslint'
  ]
}
```

**What did you expect to happen?**
For linting errors and warnings to be reported in `.vue` files implementing a `<script lang="ts">` tag.

**Are you willing to submit a pull request to fix this bug?**
Yes, but not familiar with the code base.

**Comment by zhoulang27426405** [comment] 2021-04-06 09:53
@AndreasNasman you should add [@vue/eslint-config-typescript](https://www.npmjs.com/package/@vue/eslint-config-typescript) into your project

**Comment by AndreasNasman** [comment] 2021-04-06 11:34
@zhoulang27426405 Even if I'm using [Vite](https://vitejs.dev/)?

**Comment by zhoulang27426405** [comment] 2021-04-07 07:39
@AndreasNasman  I'm not sure, i use webpack.

**Comment by 6XGate** [comment] 2021-05-27 15:12
The issue is that the `standard-with-typescript` configuration is coded to only target `.ts` and `.tsx` files via ESLint `override` and will not activate any rules for `.vue` files.  This major shortcoming of `standard-with-typescript`, but does allow you to simply add the configuration to your root `extends` list without activating rules on regular JS files.

**Comment by Divlo** [comment] 2021-07-02 15:11
> The issue is that the `standard-with-typescript` configuration is coded to only target `.ts` and `.tsx` files via ESLint `override` and will not activate any rules for `.vue` files. This major shortcoming of `standard-with-typescript`, but does allow you to simply add the configuration to your root `extends` list without activating rules on regular JS files.

Thank you for the explanation.
Do you know how can `eslint-config-standard-with-typescript` could support `.vue` files ? @6XGate 
I opened a PR: #600 but that seems to doesn't work.

**Comment by 6XGate** [comment] 2021-07-02 16:11
I think this part of the ESLint Vue plug-in docs covers that: [How to use a custom parser?](https://eslint.vuejs.org/user-guide/#how-to-use-a-custom-parser).
But I think it would make more sense to have a different config for that to be extended by the user. That config should propagate some StandardJS options to the equivalent Vue options, and then rest the current StardardTS options into the mix.

**Comment by Divlo** [comment] 2021-07-03 08:46
> I think this part of the ESLint Vue plug-in docs covers that: [How to use a custom parser?](https://eslint.vuejs.org/user-guide/#how-to-use-a-custom-parser).
> But I think it would make more sense to have a different config for that to be extended by the user. That config should propagate some StandardJS options to the equivalent Vue options, and then rest the current StardardTS options into the mix.

Right, sounds good, will close this issue and my PR.

**Closed by Divlo** 2021-07-03 08:46 UTC

**Comment by 6XGate** [comment] 2021-07-03 21:19
I wasn't suggesting it not be part of this project, but I guess that makes sense. A `standard-vue` and `standard-vue-with-typescript` probably should be their own project.

**Comment by mightyiam** [comment] 2021-07-04 01:39
> I wasn't suggesting it not be part of this project, but I guess that makes sense. A `standard-vue` and `standard-vue-with-typescript` probably should be their own project.

I'd like to say that to me it is not clear yet whether this should be a part of this project. Ideally not but if there's no reasonable alternative...
